version: '3.8'

services:
  api:
    build: ./ifta_flask_backend_api
    container_name: "iftaya-flask-backend-api"
    ports:
      - 5000:5050
    env_file:
      - ./ifta_flask_backend_api/config/.env
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker_ifta_user
      - POSTGRES_PASSWORD=docker_ifta_pass
      - POSTGRES_DB=docker_ifta_db
  ifta_nextjs:
    build:
      context: ./ifta_frontend
      dockerfile: Dockerfile
    container_name: iftaya-nextjs
    ports:
      - 3000:3000
    env_file: ./ifta_frontend/.env.local

volumes:
  postgres_data: